### ISSUE TITLE
🐛 Back quote manquante fichier `02_resume.md`

### ISSUE THREAD

**Issue by Draks898** [opt-nc/template-eae#20]
## 🐛 BUG
 **la ligne 3** il y a une apostrophe a la place d'une back cote
![image](https://github.com/opt-nc/template-eae/assets/103997763/fb59267c-79cc-4ef3-a65e-6add31b0ae50)

**A la ligne 51**, il n'y a pas de back cote du tout. Est-ce normale ? si oui pas besoin de corriger. Si non il faut les ajouter 
![image](https://github.com/opt-nc/template-eae/assets/103997763/ef36a861-1a58-40c5-b680-3c51e626080e)

**Comment by Draks898** [comment]
@adriens je ne peux pas assigner ou mettre dans un projet le ticket, je n'ai pas l'impression d'avoir les droit.

**Comment by adriens** [comment]
Bien vu @Draks898 , tu nous droppes une PR ?

**Comment by Draks898** [comment]
Non je vais en faire une.

**Comment by Draks898** [comment]
PR réalisé : 
- #21

**Comment by Draks898** [comment]
![image](https://github.com/opt-nc/template-eae/assets/103997763/87e469ef-5693-401b-bf02-53836280de01)
![image](https://github.com/opt-nc/template-eae/assets/103997763/54030bf0-dedf-4a09-8b59-9f7c37339c44)
